- _data/i18n/general.yml
- _includes/header.html
- _pages/en/client-guide.md
- _pages/en/index.md
- _pages/en/opportunities.md
- _pages/en/supplier-guide.md
- _pages/fr/guide-client.md
- _pages/fr/guide-fournisseur.md
- _pages/fr/index.md
Draft content added for:
-client user guide
-supplier user guide
-index page
-also added some text to the opportunities page.
> Added some draft content

- _pages/en/client-guide.md
> Changed client user guide text

- .editorconfig
- .github/workflows/node.js.yml
- .licensee.json
- .markdownlint.json
- _pages/en/index.md
- _pages/en/supplier-guide.md
- _pages/en/terms.md
- _posts/en/2020-06-19-fix-accessibility-issues-rocket-chat.md
- _posts/en/2020-06-22-write-summary-for-canadian-organizations-about-gdpr.md
- _posts/en/2020-07-01-wcag-21-implications-for-the-gc-and-wet-boew.md
- _posts/fr/2020-06-19-corriger-problemes-accessibilite-rocket-chat.md
- _posts/fr/2020-06-22-rediger-resume-sur-gdpr-intention-organisations-canadiennes.md
- _posts/fr/2020-07-01-implications-de-wcag-21-pour-le-gc-et-wet-boew.md
- package-lock.json
- package.json
Add Workflow to run NPM tests.  Add Markdown Lint, Editor Config and Licensee.
I didn't add Cspell because it does not like Lorem Ipsum
Fixes #27
> Add workflow and package.json with tests

- _pages/en/client-guide.md
Thought I'd try out the 'well' format on the client guide. I like the look what do you both think? I am finding the H2 font size very similar to the H1 font size though.  Can we adjust without breaking WET?
> Update client guide text and format

- _includes/header.html
Changed from:
"This is website is part of a pilot. We are learning as we go. If you see anything that isn't working or want to share your feedback, please open an issue or send us an email!"
to:
"This is website is part of a pilot and not live yet. We are currently working to make it available soon. Until then if you see anything that isn’t working or want to share your feedback, please open an issue or send us an email."
closing issue #8 
Changed font-size from 20px to 17px
closing issue #22
> Banner text change

- _data/i18n/general.yml
- _includes/howtoapply.html
- _pages/en/index.md
-Added background colour to the div sections of the index.md page (are you a developer/programmer? are you an ESDC employee?) (grey with black font)
-Added background colour to the howtoapply footer. (light grey with black font and solid border)
> Add background colour

- _pages/en/index.md
> Added a link to the MicroBuysGC twitter account

- _layouts/post.html
> Adjust the format of the opportunity post layout

- _data/i18n/general.yml
- _includes/howtoapply.html
Adjusted text and added a link to the supplier guide
> Adjust the how to apply footer

- _pages/en/supplier-guide.md
> Supplier User Guide update

- _pages/en/client-guide.md
> Client User Guide update

- _pages/en/opportunities.md
> Removed talent cloud from opportunity page

- _data/i18n/general.yml
- _includes/header.html
- _pages/en/how-this-works.md
- _pages/en/index.md
- _pages/fr/comment-ca-marche.md
The how does this work page replaces the 'Client Guide' and the text has been adjusted so that anyone interested to know the process (whether supplier or client) would be able to follow it.
> Adding new items to the Menu and created a 'How does this work' page

- _data/i18n/general.yml
- _includes/opportunitiesTable.md
- _layouts/post.html
- _posts/en/2020-06-19-fix-accessibility-issues-rocket-chat.md
- _posts/en/2020-06-22-write-summary-for-canadian-organizations-about-gdpr.md
- _posts/en/2020-07-01-wcag-21-implications-for-the-gc-and-wet-boew.md
- _posts/fr/2020-06-19-corriger-problemes-accessibilite-rocket-chat.md
- _posts/fr/2020-06-22-rediger-resume-sur-gdpr-intention-organisations-canadiennes.md
- _posts/fr/2020-07-01-implications-de-wcag-21-pour-le-gc-et-wet-boew.md
> Eastern time fix

- _includes/header.html
**Merge this PR in the morning of March 25th for UX testing!!**
closing issue #72 
@RachelMuston  I didn't delete the old version of the banner, to put it back after UX testing we will just **un**comment it ;)
> Temporary banner update

- _includes/howtoapply.html
- _pages/en/client-guide.md
- _pages/en/how-this-works.md
- _pages/en/index.md
- _pages/en/opportunities.md
- _pages/en/supplier-guide.md
- Fixed typos
closing issue #84 
- Fixed external links
closing issue #86 
-Removed "DRAFT opportunities originally posted on Github as IDEAS for GCdevex." from the Opportunity page
> External links fixed and others

- _includes/breadcrumbs.html
> Add Breadcrumbs to Opportunities page from opportunities (posts)

- _includes/opportunitiesTable.md
- assets/css/gridify.css
> Add classes and spilt style for hover and active

- _data/i18n/general.yml
- _includes/header.html
And changed 'Supplier User Guide' to 'User Guide' in the menu
> removed how this works from menu

- _includes/footer.html
> Footer - added space between the buttons

- _pages/en/opportunities.md
Also adjusted the text for 'still can't find' to 'don't see...'
> Added an icon for twitter

- _includes/breadcrumbs.html
> Add breadcrumb back to User Guide from Terms and Conditions page

- _layouts/post.html
- _pages/en/index.md
> Add container div for opportunities - fix W3C button inside a

- _pages/en/index.md
> remove mention of OSME from index page

- _pages/en/opportunities.md
- _pages/fr/opportunites.md
Also made a small fix to a link on the english page.
> French opportunities page

- _includes/breadcrumbs.html
- _includes/footer.html
- _includes/header.html
- _includes/pre-footer.html
- _layouts/default.html
- index.html
Tested using axe-core add-on for Firefox. 
The only issue left is `Ensures landmarks are unique`.
Because we have several `nav` elements.  Canada.ca had already fixed most of the issues but still have more than one `nav`.
> Fix axe-Core issues

- _pages/en/opportunities.md
- _pages/en/user-guide.md
> added text from OSME

- _includes/footer.html
- _includes/head.html
- _includes/howtoapply.html
- _includes/opportunitiesTable.md
- _includes/pre-footer.html
- _layouts/post.html
- _pages/en/index.md
- _pages/en/terms.md
- _pages/fr/index.md
- _pages/fr/termes.md
- assets/css/style.css
> Move styles to css file

- _includes/pre-footer.html
> Change section to div to alert with no heading

- _includes/opportunitiesTable.md
- _includes/replaceFrenchMonth.md
- _layouts/post.html
> Change closing date to long format - add translations

- _pages/en/index.md
- _pages/en/terms.md
- _pages/fr/index.md
- _pages/fr/termes.md
- assets/css/style.css
Initial commits fix #169 and #171
> Remove html and BR tags

- _posts/fr/gabarit-opportunite.md
Also removed instructional text in the english template for now as we do not have this in french (and don't need it for this first opportunity as we have already written it)
> Added french opportunity template

- _pages/en/opportunities.md
- _pages/fr/opportunites.md
> Twitter link in a new tab

- _pages/en/faq.md
- _pages/fr/faq.md
Propose changing `<strong>` by `<details><summary>`
Also adjusts the inner HTML with `blockquote` and `a` elements
> Switch strong with details

- _includes/opportunitiesTable.md
Temporary workaround for issue #194
> Make table responsive

- _data/i18n/general.yml
- _includes/opportunitiesTable.md
- _layouts/post.html
- _pages/en/user-guide.md
- _pages/fr/guide-utilisateur.md
- _posts/en/2021-06-23-building-custom-Azure-marketplace-policies.md
- _posts/fr/2021-06-23-elaboration-de-politiques-personnalisees-pour-azure-marketplace.md
changed the dates (changed the closing date from July 5 to 12, changed the selection date from the 9th to the 16th, changed the work delivery date from the 16th to the 23rd)  and eligibility (to include permanent residents and foreign students (as well as foreign workers). Also updated eligibility for the pilot as a whole (in the user guide)
> updates to Azure opportunity

- _data/i18n/general.yml
removed 'prototype' and added text from the main page of the site
> update to site description

- _includes/opportunitiesTable.md
> Add calendar + strong

- _data/i18n/general.yml
- _pages/en/user-guide.md
- _pages/fr/guide-utilisateur.md
> Accessibility documents

- _pages/en/terms.md
- _pages/fr/termes.md
> Change underlines to span with arial label

- _pages/en/index.md
- _pages/fr/index.md
- assets/css/style.css
> Add overflow override for paragraphs

- _layouts/default.html
- _layouts/post.html
> Add .wb-cont to main containers

- _pages/en/index.md
- _pages/fr/index.md
> Remove alt text

- _pages/en/index.md
- _pages/fr/index.md
> Adjusted title and h2

- _includes/opportunitiesTable.md
> Add missing th + remove responsive table

- assets/css/style.css
Pushed the html changes without the css changes... :sweat_smile:
> Add missing css updates

- _includes/opportunitiesTable.html
After running W3C HTML validator, removing <section> tags
> Remove sections

- _pages/en/opportunities.md
- _pages/fr/opportunites.md
Added the link to the mailing list and adjusted the formatting. Moved the 'don't see an opportunity that matches your skills below the opportunities table.
Not sure how I feel about the blue buttons and the arrows in the buttons here.  Would it be better if the buttons were grey? No arrow?
> Added the mailing list form and other changes

- _pages/en/index.md
- _pages/fr/index.md
> Updated the index page 'calling all coders'

- _pages/en/user-guide.md
- _pages/fr/guide-utilisateur.md
Fyi the french text needs a review.
> Add an example evaluation criteria and example answers to the User Guide

- _layouts/default.html
> fixed lang

- _data/i18n/general.yml
> Added en anglais seulement to the button in the footer

- assets/css/style.css
Closes #246 (see it for details).
> Fix bad reflow on some screen resolutions
